# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectboard', '0002_auto_20170207_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qp',
            options={},
        ),
    ]
